services:
  db: 
    image: mysql:8
    container_name: database-tracer
    ports: 
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}  
      TZ: ${TZ}
    command: --default-time-zone=+00:00  
    volumes: 
      - db_data:/var/lib/mysql

  be: 
    build : 
      context : .
      dockerfile : Dockerfile
    container_name : be-tracer
    env_file :
      - .env
    environment:
      - CI=true
      - NODE_ENV=${NODE_ENV:-development}
      - HOT_RELOAD=true
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}?timezone=UTC&authPlugin=mysql_native_password
    ports : 
      - "5000:5000"
    depends_on : 
      - db
    volumes : 
      - ./:/app
      - node_modules_data:/app/node_modules

volumes:
  db_data:
  node_modules_data:
